sudo: false

language: node_js
node_js:
- '6'

addons:
  sauce_connect: true

notifications:
    on_success: always
    on_failure: always

install:
- npm install

before_script:
- npm install

script:
- npm run unit.test
- npm run test.ci
