sudo: false

language: node_js
node_js:
- '6'

addons:
  sauce_connect: true
  artifacts:
    key: $TRAVIS_KEY
    secret: $TRAVIS_SECRET
    bucket: wswebcreation-image-comparison
    paths:
    - .tmp/
    target_paths: travis-builds/$TRAVIS_BUILD_NUMBER
    working_dir: travis-builds
    s3_region: us-east-1
    permissions: public-read

notifications:
    on_success: always
    on_failure: always

install:
- npm install

before_script:
- npm install

script:
- npm run unit.test
- npm run test.ci
